---
version: "3"

volumes:
  data:

services:

  fexapi:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    depends_on:
      - "db"
    environment:
      - DYNACONF_DATABASE_URL="postgresql://fexservice:password@db/fexservice"
    volumes:
      - ./fexapi:/fexapi
    ports:
      - "8000:8000"

  fexservice:
    build: 
      context: .
      dockerfile: ./docker/service/Dockerfile
    restart: always
    depends_on:
      - "db"
    environment:
      - DYNACONF_DATABASE_URL="postgresql+psycopg2://fexservice:password@db/fexservice"
    volumes:
      - ./service:/service

  db:
    image: postgres:12.1
    restart: always
    environment:
      - POSTGRES_USER=fexservice
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fexservice
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
