---
version: "3"

volumes:
  data:

services:

  fexservice:
    build: .
    restart: always
    depends_on:
      - "db"

  db:
    image: postgres:12.1
    restart: always
    environment:
      DYNACONF_DATABASE_URL: "@jinja postgresql+psycopg2://{this[DB_USER]}:{this[DB_PASS]}@db/{this[DB_NAME]}"
    volumes:
      - data:/var/lib/postgresql/data
